// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxQH3A8H3Cuk9RT6pLT3h1_i5Clfb0AAQ',
    appId: '1:1032807957835:web:9beeb324248130b36214ce',
    messagingSenderId: '1032807957835',
    projectId: 'fitd-587f8',
    authDomain: 'fitd-587f8.firebaseapp.com',
    storageBucket: 'fitd-587f8.appspot.com',
    measurementId: 'G-VXMETBG85Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsQRMfsbfjCjEY3WZuVTtnAinC6WGdlZs',
    appId: '1:1032807957835:android:c37ac095550985036214ce',
    messagingSenderId: '1032807957835',
    projectId: 'fitd-587f8',
    storageBucket: 'fitd-587f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSnI_cdMjYT36Fqc2hDwGjhxenEYKQ5eA',
    appId: '1:1032807957835:ios:b640bc841ac31efb6214ce',
    messagingSenderId: '1032807957835',
    projectId: 'fitd-587f8',
    storageBucket: 'fitd-587f8.appspot.com',
    iosClientId: '1032807957835-njqag2vva437hre97tj7ugol74ct2mfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitDbProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSnI_cdMjYT36Fqc2hDwGjhxenEYKQ5eA',
    appId: '1:1032807957835:ios:b640bc841ac31efb6214ce',
    messagingSenderId: '1032807957835',
    projectId: 'fitd-587f8',
    storageBucket: 'fitd-587f8.appspot.com',
    iosClientId: '1032807957835-njqag2vva437hre97tj7ugol74ct2mfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitDbProject',
  );
}
